# include the definitions of LIBS and COMPLEX
include ../../Make.config

NAME   = adapt-ortho
HERMES = ../../lib/libhermes2d-$(CC)-O-real.a
FLAGS = -O3 -DNDEBUG
#FLAGS = -ggdb

include ../Make.common
