# include the definitions of LIBS and COMPLEX
include ../../Make.config

NAME   = adapt
HERMES = ../../lib/libhermes2d-$(CC)-O-real.a
#FLAGS  = -O3 -DNDEBUG -ggdb -pg
FLAGS = -O3 -DNDEBUG
#FLAGS = -ggdb

include ../Make.common
