include ../../Make.config

NAME   = scratch
HERMES = ../../lib/libhermes2d-$(CC)-g-cplx.a
FLAGS  = -ggdb -DCOMPLEX
#FLAGS = -O3 -DNDEBUG -DCOMPLEX
#FLAGS = -O3 -DNDEBUG
#FLAGS = -ggdb

include ../Make.common
