include ../../Make.config

#CC = icc
NAME   = navier-stokes
HERMES = ../../lib/libhermes2d-$(CC)-O-real.a
FLAGS  = -O3 -DNDEBUG 
# -ftree-vectorize -msse2 -ftree-vectorizer-verbose=5
# -axW -parallel -vec-report3
#FLAGS = -ggdb

include ../Make.common
