#!/bin/bash

cat $1 \
| sed 's|~| |g' \
| sed 's|\\_|_|g' \
| sed 's|{\\tt \([^}]*\)}|`\1`|g' \
| sed 's|\\verb"\([^"]*\)"|`\1`|g' \
| sed 's|{\\it \([^}]*\)}|\x27\x27\1\x27\x27|g' \
| sed 's|\\emph{\([^}]*\)}|\x27\x27\1\x27\x27|g' \
| sed 's|{\\em \([^}]*\)}|\x27\x27\1\x27\x27|g' \
| sed 's|$$.*$$|{{{\n#!latex\n&\n}}}|g' \
| sed 's|\\label{[^}]*}||g' \
| sed 's|\\index{[^}]*}||g' \
| sed 's|\\begin{equation}|{{{\n#!latex\n$$|g' \
| sed 's|\\end{equation}|$$\n}}}|g' \
| sed 's|\\begin{lstlisting}|{{{\n#!c|g' \
| sed 's|\\end{lstlisting}|}}}|g' \
| sed 's|\\lstset{[^}]*}||g' \
| sed 's|\\subsection{\([^}]*\)}|= \1 =|g' \
| sed 's|``\([^\x27]*\)\x27\x27|"\1"|g' \
| sed 's|``\([^"]*\)"|"\1"|g'
