#ifndef __HERMES2D_SEA_BREEZE_PARAMS_H
#define __HERMES2D_SEA_BREEZE_PARAMS_H

/* This file is generated by equations.py

   Just modify the python script if you want to change the quantities. Note
   that all the quantities in this file are related, so you *cannot* just
   change R or g (say) without also recalculating p, T and rho.
*/

// Everything is in SI units
// initial presure p in Pascals
#define p_z(z) (100000 - 11.3653418526412*(z))
// initial temperature T in Kelvin
#define T_z(z) (300.5 - 0.0341528522671867*(z))
// initial gas density
#define rho_z(z) (1.15894233531748)

// other physical constants
#define R 287.14           // Gas constant
#define g 9.80665           // gravitational acceleration
#define c_v 20.8       // specific heat capacity

// main characteristic constants
#define l_r 10000.0
#define u_r 95.0
#define rho_r 1.1
// other characteristic constants
#define t_r (l_r/u_r)
#define p_r (rho_r*u_r*u_r)
#define g_r (l_r/(t_r*t_r))

#endif