#ifndef __HERMES2D_SEA_BREEZE_PARAMS_H
#define __HERMES2D_SEA_BREEZE_PARAMS_H

/* This file is generated by equations.py

   Just modify the python script if you want to change the quantities. Note
   that all the quantities in this file are related, so you *cannot* just
   change R or g (say) without also recalculating p, T and rho.
*/

// Everything is in SI units
// initial presure p in Pascals
#define p_z(z) (100000 - 11.3653418526412*(z) + 0.00052954*pow((z),2) - 9.38e-9*pow((z),3))
// initial temperature T in Kelvin
#define T_z(z) (300.5 - 0.00615074338860148*(z) + 2.74087847242543e-7*pow((z),2) + 1.25829142493795e-11*pow((z),3))
// initial gas density
#define rho_z(z) (1.15894233531748 - 0.000107996104684066*(z) + 2.86948142331989e-9*pow((z),2))

// other physical constants
#define R 287.14           // Gas constant
#define g 9.80665           // gravitational acceleration
#define c_v 20.8       // specific heat capacity

#endif